/* "PLAYWRIGHT_Helpers" plugin
1. DESCRIPTION:
- The plugin can be used for updating project with already prepared commands
2. USAGE:
- Can be used for existed and new project
1. Choose command You are interested in
2. Command is displayed in terminal
3. After confirmation by enter - the command is executed
!!! Some commands are run right after clicking - mostly those which are set in package.json --> scripts
The Plugin contains also commands composer where user can:
1. Compose the command by choosing elements in "Command Composer" section
2. Update existed command using "Command Composer" section
3. Prepare command script from scratch
!!! The plugin also allows to use playwright embedded commands for playing around with Playwright
*/

import { test, expect } from '@playwright/test';

test.describe('My first generated by plugins test set', () => {
  test.beforeEach(async ({ page }) => {
    // TODO: open the page
    await page.goto('https://www.wp.pl');
  });

  test('First generated test', async ({ page }) => {
    // Arrange:
    const validURL = 'https://www.wp.pl';
    // Act:
    // Assert:
    await expect(page).toHaveURL(validURL);
  });
});
